SalaDeEnsaio/Controllers/ContasReceberController.cs
using SalaDeEnsaio.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace SalaDeEnsaio.Controllers
{
    public class ContasReceberController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ContasReceber
        public ActionResult Index()
        {
            var contasReceber = db.ContasReceber
                                    .Include(c => c.Pessoa)
                                    .OrderByDescending(x => x.Vencimento);

            return View(contasReceber.ToList());
        }

        // GET: ContasReceber/Create
        public ActionResult Create()
        {
            var pessoas = db.Pessoas.OrderBy(x => x.Nome);
            ViewBag.PessoaId = new SelectList(pessoas, "Id", "Nome");
            return View();
        }

        // POST: ContasReceber/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descricao,Valor,Recebido,PessoaId,Vencimento,Turma")] ContaReceber contaReceber)
        {
            if (ModelState.IsValid)
            {
                db.ContasReceber.Add(contaReceber);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PessoaId = new SelectList(db.Pessoas, "Id", "Nome", contaReceber.PessoaId);
            return View(contaReceber);
        }

        // GET: ContasReceber/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContaReceber contaReceber = db.ContasReceber.Find(id);
            if (contaReceber == null)
            {
                return HttpNotFound();
            }

            var pessoas = db.Pessoas.OrderBy(x => x.Nome);
            ViewBag.PessoaId = new SelectList(pessoas, "Id", "Nome", contaReceber.PessoaId);

            return View(contaReceber);
        }

        // POST: ContasReceber/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descricao,Valor,Recebido,PessoaId,Vencimento,Turma")] ContaReceber contaReceber)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contaReceber).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PessoaId = new SelectList(db.Pessoas, "Id", "Nome", contaReceber.PessoaId);
            return View(contaReceber);
        }

        // GET: ContasReceber/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContaReceber contaReceber = db.ContasReceber.Find(id);
            if (contaReceber == null)
            {
                return HttpNotFound();
            }
            return View(contaReceber);
        }

        // POST: ContasReceber/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            ContaReceber contaReceber = db.ContasReceber.Find(id);
            db.ContasReceber.Remove(contaReceber);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SalaDeEnsaio/Views/ContasReceber/Create.cshtml
@model SalaDeEnsaio.Models.ContaReceber

@{
    ViewBag.Title = "Inserir conta a receber";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @RenderPage("_Form.cshtml")
}

SalaDeEnsaio/Views/ContasReceber/Delete.cshtml
@model SalaDeEnsaio.Models.ContaReceber

@{
    ViewBag.Title = "Excluir";
}

<h2>@ViewBag.Title</h2>

<h3>Tem certeza de que deseja excluir?</h3><small>Esta alteração é irreversível.</small>
<div>
    <h4>Conta a receber</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pessoa.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pessoa.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Recebido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Recebido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vencimento)
        </dt>

        <dd>            
            @(string.Format("{0}/{1}/{2}",
                Model.Vencimento.Day.ToString().PadLeft(2,'0'),
                Model.Vencimento.Month.ToString().PadLeft(2, '0'),
                Model.Vencimento.Year))
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" /> |
            @Html.ActionLink("Voltar para a lista", "Index")
        </div>
    }
</div>

SalaDeEnsaio/Views/ContasReceber/Edit.cshtml
@model SalaDeEnsaio.Models.ContaReceber

@{
    ViewBag.Title = "Editar conta a receber";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.Id)

    @RenderPage("_Form.cshtml")
}

SalaDeEnsaio/Views/ContasReceber/Index.cshtml
@model IEnumerable<SalaDeEnsaio.Models.ContaReceber>

@{
    ViewBag.Title = "Contas a receber";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-2">
        @Html.ActionLink("Inserir conta a receber", "Create", new { }, new { @class = "btn btn-primary" })
    </div>
    <div class="col-lg-4">
        <input type="text" id="search" class="form-control" placeholder="Pesquisar" autofocus />
    </div>
</div>
<br />
<table class="table table-condensed">
    <thead>
        <tr>
            <th>#</th>
            <th>
                @Html.DisplayNameFor(model => model.Vencimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PessoaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turma)
            </th>                        
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="recebido @(item.Recebido.ToString().ToLower())">
                <td>
                    <a href="@Url.Action("Edit","ContasReceber", new { id = item.Id })" class="btn" title="Editar">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </a>
                    <a href="@Url.Action("Delete","ContasReceber", new { id = item.Id })" class="btn" title="Excluir">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </a>
                </td>
                <td>
                    @(string.Format("{0}/{1}/{2}",
                        item.Vencimento.Day.ToString().PadLeft(2, '0'),
                        item.Vencimento.Month.ToString().PadLeft(2, '0'),
                        item.Vencimento.Year))
                </td>
                <td align="right">
                    <div class="compose-column">
                        @(item.Valor.ToString("c"))
                        <div class="recebido @(item.Recebido.ToString().ToLower())"></div>
                    </div>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pessoa.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Turma)
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script src="~/Scripts/app/contas-receber.js"></script>
}

SalaDeEnsaio/Views/ContasReceber/_Form.cshtml
@model SalaDeEnsaio.Models.ContaReceber

@Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Conta a receber</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.PessoaId, "Pessoa", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("PessoaId", null, "Selecione...", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PessoaId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Turma, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Turma, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Turma, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Vencimento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Vencimento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Vencimento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Recebido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Recebido)
                @Html.ValidationMessageFor(model => model.Recebido, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
        
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-primary" />
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Voltar para a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}